Repository exteranto/framework, pull requests merged in 2018-12, with the labels that each got.

#18 [global] moved tslint config and improved buid scripts
  bin/script.sh
  lib/aop/package.json
  lib/aop/tslint.json
  lib/cache/package.json
  lib/cache/tslint.json
  lib/compatibility/package.json
  lib/compatibility/tslint.json
  lib/core/package.json
  lib/core/src/App.ts
  lib/events/package.json
  lib/events/src/Dispatcher.ts
  lib/events/tslint.json
  lib/exceptions/package.json
  lib/exceptions/tslint.json
  lib/ioc/package.json
  lib/ioc/tslint.json
  lib/management/package.json
  lib/management/tslint.json
  lib/messaging/package.json
  lib/messaging/tslint.json
  lib/storage/package.json
  lib/storage/tslint.json
  lib/support/package.json
  lib/support/tslint.json
  lib/tabs/package.json
  lib/tabs/tslint.json
  tslint.json
Labels: merge last

#21 Feature cookies apis
  lib/exceptions/src/index.ts
  lib/exceptions/src/storage/index.ts
  lib/storage/package-lock.json
  lib/storage/package.json
  lib/storage/src/Cookies.ts
  lib/storage/src/CookiesProvider.ts
  lib/storage/src/StorageProvider.ts
  lib/storage/src/chrome/Cookies.ts
  lib/storage/src/extensions/Cookies.ts
  lib/storage/src/index.ts
  lib/storage/test/setup.ts
  lib/storage/test/spec/ChromeStorage.spec.ts
  lib/storage/test/spec/ExtensionsStorage.spec.ts
  lib/storage/test/spec/SafariStorage.spec.ts
  lib/storage/test/spec/cookies/ChromeCookies.spec.ts
  lib/storage/test/spec/cookies/ExtensionsCookies.spec.ts
  lib/storage/test/spec/cookies/SafariCookies.spec.ts
  lib/storage/test/spec/cookies/index.spec.ts
  lib/storage/test/spec/store/ChromeStorage.spec.ts
  lib/storage/test/spec/store/ExtensionsStorage.spec.ts
  lib/storage/test/spec/store/SafariStorage.spec.ts
  lib/storage/test/spec/store/index.spec.ts
  lib/tabs/src/chrome/events.ts
  tslint.json
Labels: api coverage

#15 [management] Browser action service
  lib/exceptions/src/index.ts
  lib/exceptions/src/tabs/index.ts
  lib/management/package-lock.json
  lib/management/package.json
  lib/management/src/ManagementProvider.ts
  lib/management/src/browserAction/BrowserAction.ts
  lib/management/src/browserAction/chrome/BrowserAction.ts
  lib/management/src/browserAction/extensions/BrowserAction.ts
  lib/management/src/browserAction/index.ts
  lib/management/src/browserAction/safari/BrowserAction.ts
  lib/management/src/index.ts
  lib/management/src/permissions/PermissionManagerProvider.ts
  lib/management/src/permissions/index.ts
  lib/management/test/safari.ts
  lib/management/test/setup.ts
  lib/management/test/spec/browserAction/BrowserAction.spec.ts
  lib/management/test/spec/browserAction/ChromeBrowserAction.spec.ts
  lib/management/test/spec/browserAction/ExtensionsBrowserAction.spec.ts
  lib/management/test/spec/browserAction/SafariBrowserAction.spec.ts
Labels: question
