Repository exteranto/framework, pull requests merged in 2019-01, with the labels that each got.

#23 Feature runtime information
  bin/script.sh
  lib/aop/package-lock.json
  lib/cache/package-lock.json
  lib/compatibility/package-lock.json
  lib/core/package-lock.json
  lib/events/package-lock.json
  lib/events/package.json
  lib/events/src/Dispatcher.ts
  lib/events/src/ListenerBag.ts
  lib/events/test/spec/Dispatcher.spec.ts
  lib/exceptions/package-lock.json
  lib/exceptions/src/index.ts
  lib/ioc/package-lock.json
  lib/management/package-lock.json
  lib/management/src/ManagementProvider.ts
  lib/management/src/runtime/Runtime.ts
  lib/management/src/runtime/chrome/Runtime.ts
  lib/management/src/runtime/chrome/events.ts
  lib/management/src/runtime/extensions/Runtime.ts
  lib/management/src/runtime/extensions/events.ts
  lib/management/src/runtime/index.ts
  lib/management/src/runtime/safari/Runtime.ts
  lib/management/src/runtime/safari/events.ts
  lib/management/test/safari.ts
  lib/management/test/setup.ts
  lib/management/test/spec/browserAction/BrowserAction.spec.ts
  lib/management/test/spec/browserAction/ChromeBrowserAction.spec.ts
  lib/management/test/spec/browserAction/ExtensionsBrowserAction.spec.ts
  lib/management/test/spec/browserAction/SafariBrowserAction.spec.ts
  lib/management/test/spec/permissions/ChromePermissions.spec.ts
  lib/management/test/spec/permissions/ExtensionsPermissions.spec.ts
  lib/management/test/spec/permissions/Permissions.spec.ts
  lib/management/test/spec/permissions/SafariPermissions.spec.ts
  lib/management/test/spec/runtime/ChromeRuntime.spec.ts
  lib/management/test/spec/runtime/ExtensionsRuntime.spec.ts
  lib/management/test/spec/runtime/Runtime.spec.ts
  lib/management/test/spec/runtime/SafariRuntime.spec.ts
  lib/messaging/package-lock.json
  lib/storage/package-lock.json
  lib/storage/src/Cookies.ts
  lib/storage/test/setup.ts
  lib/support/package-lock.json
  lib/tabs/package-lock.json
  lib/tabs/src/Tabs.ts
  lib/test/mocks/localStorage.ts
  lib/test/mocks/safari.ts
Labels: api coverage, enhancement

#27 [management][safari] finished browser action for Safari
  lib/management/src/browserAction/BrowserAction.ts
  lib/management/src/browserAction/chrome/BrowserAction.ts
  lib/management/src/browserAction/extensions/BrowserAction.ts
  lib/management/src/browserAction/safari/BrowserAction.ts
  lib/management/test/spec/browserAction/ChromeBrowserAction.spec.ts
  lib/management/test/spec/browserAction/ExtensionsBrowserAction.spec.ts
  lib/management/test/spec/browserAction/SafariBrowserAction.spec.ts
Labels: api coverage

#20 [core] asset publishing
  lib/core/package-lock.json
  lib/core/package.json
  lib/core/src/App.ts
  lib/core/src/Router.ts
  lib/core/src/index.ts
  lib/core/test/spec/App.spec.ts
  lib/core/test/spec/Router.spec.ts
  lib/exceptions/src/core/index.ts
  lib/exceptions/src/index.ts
  lib/support/src/Provider.ts
Labels: enhancement

#29 Feature messaging event
  lib/messaging/src/safari/Messaging.ts
  lib/messaging/test/spec/SafariMessaging.spec.ts
  lib/tabs/src/safari/ResponseHub.ts
  lib/tabs/src/safari/Tab.ts
  lib/tabs/src/safari/Tabs.ts
  lib/tabs/src/safari/events.ts
Labels: enhancement

#37 [core] window load event
  bin/script.sh
  lib/aop/package-lock.json
  lib/cache/package-lock.json
  lib/cache/package.json
  lib/cache/test/setup.ts
  lib/compatibility/package-lock.json
  lib/compatibility/package.json
  lib/compatibility/test/setup.ts
  lib/compatibility/test/spec/Comb.spec.ts
  lib/core/package-lock.json
  lib/core/package.json
  lib/core/src/App.ts
  lib/core/test/setup.ts
  lib/core/test/spec/App.spec.ts
  lib/core/test/spec/Router.spec.ts
  lib/events/package-lock.json
  lib/exceptions/package-lock.json
  lib/ioc/package-lock.json
  lib/management/test/setup.ts
  lib/messaging/package-lock.json
  lib/messaging/test/setup.ts
  lib/storage/package-lock.json
  lib/storage/test/setup.ts
  lib/support/package-lock.json
  lib/tabs/package-lock.json
  lib/tabs/test/setup.ts
Labels: api coverage

#38 Feature badge click event
  lib/management/package-lock.json
  lib/management/src/ManagementProvider.ts
  lib/management/src/browserAction/BrowserAction.ts
  lib/management/src/browserAction/chrome/BrowserAction.ts
  lib/management/src/browserAction/extensions/BrowserAction.ts
  lib/management/src/browserAction/safari/BrowserAction.ts
  lib/management/src/runtime/chrome/events.ts
  lib/management/src/runtime/extensions/events.ts
  lib/management/src/runtime/safari/events.ts
  lib/management/test/spec/browserAction/ChromeBrowserAction.spec.ts
  lib/management/test/spec/browserAction/ExtensionsBrowserAction.spec.ts
  lib/management/test/spec/runtime/ChromeRuntime.spec.ts
  lib/management/test/spec/runtime/ExtensionsRuntime.spec.ts
  lib/tabs/package-lock.json
  lib/tabs/package.json
  lib/tabs/src/Tabs.ts
  lib/tabs/src/chrome/Tabs.ts
  lib/tabs/src/extensions/Tabs.ts
  lib/tabs/src/safari/Tabs.ts
  lib/tabs/test/spec/ChromeTabs.spec.ts
  lib/tabs/test/spec/ExtensionsTabs.spec.ts
Labels: api coverage

#36 [messaging] message rejection
  lib/aop/package-lock.json
  lib/cache/package-lock.json
  lib/compatibility/package-lock.json
  lib/core/package-lock.json
  lib/events/package-lock.json
  lib/exceptions/package-lock.json
  lib/ioc/package-lock.json
  lib/management/package-lock.json
  lib/messaging/package-lock.json
  lib/messaging/src/Messaging.ts
  lib/messaging/src/chrome/Messaging.ts
  lib/messaging/src/extensions/Messaging.ts
  lib/messaging/src/safari/Messaging.ts
  lib/messaging/test/spec/ChromeMessaging.spec.ts
  lib/messaging/test/spec/ExtensionsMessaging.spec.ts
  lib/messaging/test/spec/_Messaging.spec.ts
  lib/storage/package-lock.json
  lib/support/package-lock.json
  lib/tabs/package-lock.json
  lib/tabs/src/safari/ResponseHub.ts
Labels: enhancement

#40 middleware implemented and tested
  lib/cache/package-lock.json
  lib/compatibility/package-lock.json
  lib/core/package-lock.json
  lib/events/package-lock.json
  lib/events/package.json
  lib/events/src/Dispatcher.ts
  lib/events/src/ListenerBag.ts
  lib/events/src/Middleware.ts
  lib/events/src/index.ts
  lib/events/test/spec/Dispatcher.spec.ts
  lib/exceptions/package-lock.json
  lib/management/package-lock.json
  lib/management/test/spec/browserAction/ChromeBrowserAction.spec.ts
  lib/management/test/spec/browserAction/ExtensionsBrowserAction.spec.ts
  lib/management/test/spec/runtime/ChromeRuntime.spec.ts
  lib/management/test/spec/runtime/ExtensionsRuntime.spec.ts
  lib/management/test/spec/runtime/SafariRuntime.spec.ts
  lib/messaging/package-lock.json
  lib/storage/package-lock.json
  lib/storage/test/spec/cookies/ChromeCookies.spec.ts
  lib/storage/test/spec/cookies/ExtensionsCookies.spec.ts
  lib/tabs/package-lock.json
Labels: enhancement

#45 Bug register all safari tabs
  lib/tabs/src/safari/events.ts
Labels: bug

#49 Bug messaging fixes
  lib/api/src/messaging/chrome/Messaging.ts
  lib/api/src/messaging/extensions/Messaging.ts
  lib/api/src/messaging/safari/Messaging.ts
  lib/api/src/tabs/chrome/Tab.ts
  lib/api/src/tabs/extensions/Tab.ts
  lib/api/tsconfig.json
  lib/core/tsconfig.json
  lib/utils/tsconfig.json
Labels: bug

#58 Added exit command
  lib/api/package.json
  lib/api/test/mocks/setup.ts
  lib/api/test/mocks/spec/mocks.spec.ts
  lib/core/package.json
  lib/utils/package.json
Labels: bug

#71 Added match function
  lib/core/src/structures/optional/None.ts
  lib/core/src/structures/optional/Optional.ts
  lib/core/src/structures/optional/Some.ts
  lib/core/test/structures/spec/Optional.spec.ts
Labels: enhancement

#79 finished reviewing core docs
  lib/core/src/app/App.ts
  lib/core/src/app/Router.ts
  lib/core/src/app/events.ts
  lib/core/src/events/Dispatcher.ts
  lib/core/src/events/Listener.ts
  lib/core/src/events/ListenerBag.ts
  lib/core/src/events/Middleware.ts
  lib/core/src/events/RegistersNativeEvents.ts
  lib/core/src/ioc/Annotations.ts
  lib/core/src/ioc/Container.ts
  lib/core/src/ioc/Dependency.ts
  lib/core/src/structures/optional/None.ts
  lib/core/src/structures/optional/Optional.ts
  lib/core/src/structures/optional/Some.ts
  lib/core/src/structures/pipeline/Pipeline.ts
  lib/core/src/structures/queue/PriorityQueue.ts
  lib/core/src/structures/queue/Queue.ts
  lib/core/src/structures/queue/Sortable.ts
  lib/core/src/structures/queue/index.ts
  lib/core/src/support/Provider.ts
  lib/core/src/support/Utils.ts
  lib/core/test/spec/app/Router.spec.ts
  lib/core/test/spec/structures/Optional.spec.ts
  lib/exceptions/src/global/index.ts
  lib/exceptions/src/index.ts
  lib/utils/src/aop/Annotations.ts
  lib/utils/src/aop/AspectContainer.ts
  lib/utils/src/cache/Annotations.ts
  lib/utils/src/cache/Cache.ts
  lib/utils/src/compatibility/Comb.ts
  lib/utils/src/compatibility/VersionResolver.ts
  lib/utils/src/compatibility/Versioning.ts
  tslint.json
Labels: beekeeping

#81 Feature api jsdocs
  lib/api/src/browserAction/BrowserAction.ts
  lib/api/src/browserAction/BrowserActionProvider.ts
  lib/api/src/browserAction/chrome/BrowserAction.ts
  lib/api/src/browserAction/extensions/BrowserAction.ts
  lib/api/src/browserAction/safari/BrowserAction.ts
  lib/api/src/cookies/Cookies.ts
  lib/api/src/cookies/CookiesProvider.ts
  lib/api/src/cookies/chrome/Cookies.ts
  lib/api/src/cookies/events.ts
  lib/api/src/cookies/extensions/Cookies.ts
  lib/api/src/cookies/safari/Cookies.ts
  lib/api/src/extension/Extension.ts
  lib/api/src/messaging/Message.ts
  lib/api/src/messaging/Messaging.ts
  lib/api/src/messaging/safari/Messaging.ts
  lib/api/src/permissions/Annotations.ts
  lib/api/src/permissions/PermissionManager.ts
  lib/api/src/permissions/PermissionManagerProvider.ts
  lib/api/src/permissions/chrome/PermissionManager.ts
  lib/api/src/permissions/extensions/PermissionManager.ts
  lib/api/src/permissions/safari/PermissionManager.ts
  lib/api/src/runtime/Runtime.ts
  lib/api/src/runtime/RuntimeProvider.ts
  lib/api/src/runtime/events.ts
  lib/api/src/runtime/safari/events.ts
  lib/api/src/storage/Storage.ts
  lib/api/src/storage/StorageProvider.ts
  lib/api/src/storage/chrome/Storage.ts
  lib/api/src/storage/events.ts
  lib/api/src/storage/extensions/Storage.ts
  lib/api/src/storage/safari/Storage.ts
  lib/api/src/tabs/TabInterface.ts
  lib/api/src/tabs/Tabs.ts
  lib/api/src/tabs/TabsProvider.ts
  lib/api/src/tabs/chrome/Tab.ts
  lib/api/src/tabs/chrome/Tabs.ts
  lib/api/src/tabs/events.ts
  lib/api/src/tabs/extensions/Tab.ts
  lib/api/src/tabs/extensions/Tabs.ts
  lib/api/src/tabs/safari/ResponseHub.ts
  lib/api/src/tabs/safari/Tab.ts
  lib/api/src/tabs/safari/Tabs.ts
  lib/api/src/tabs/safari/events.ts
  lib/api/test/spec/browserAction/chrome.ts
  lib/api/test/spec/browserAction/extensions.ts
  lib/api/test/spec/cookies/chrome.ts
  lib/api/test/spec/cookies/extensions.ts
  lib/api/test/spec/cookies/safari.ts
  lib/api/test/spec/permissions/safari.ts
  lib/exceptions/src/index.ts
  lib/exceptions/src/storage/index.ts
  lib/exceptions/test/spec/Exceptions.spec.ts
Labels: beekeeping

#82 bunch of cs fixes
  lib/api/src/browserAction/BrowserAction.ts
  lib/api/src/browserAction/BrowserActionProvider.ts
  lib/api/src/browserAction/chrome/BrowserAction.ts
  lib/api/src/browserAction/events.ts
  lib/api/src/browserAction/extensions/BrowserAction.ts
  lib/api/src/browserAction/safari/BrowserAction.ts
  lib/api/src/cookies/Cookies.ts
  lib/api/src/cookies/CookiesProvider.ts
  lib/api/src/cookies/chrome/Cookies.ts
  lib/api/src/cookies/events.ts
  lib/api/src/cookies/extensions/Cookies.ts
  lib/api/src/cookies/safari/Cookies.ts
  lib/api/src/extension/ExtensionProvider.ts
  lib/api/src/extension/chrome/Extension.ts
  lib/api/src/extension/extensions/Extension.ts
  lib/api/src/extension/safari/Extension.ts
  lib/api/src/messaging/Message.ts
  lib/api/src/messaging/Messaging.ts
  lib/api/src/messaging/MessagingProvider.ts
  lib/api/src/messaging/chrome/Messaging.ts
  lib/api/src/messaging/extensions/Messaging.ts
  lib/api/src/messaging/safari/Messaging.ts
  lib/api/src/permissions/PermissionManager.ts
  lib/api/src/permissions/PermissionManagerProvider.ts
  lib/api/src/permissions/chrome/PermissionManager.ts
  lib/api/src/permissions/extensions/PermissionManager.ts
  lib/api/src/permissions/safari/PermissionManager.ts
  lib/api/src/runtime/Runtime.ts
  lib/api/src/runtime/RuntimeProvider.ts
  lib/api/src/runtime/chrome/Runtime.ts
  lib/api/src/runtime/events.ts
  lib/api/src/runtime/extensions/Runtime.ts
  lib/api/src/runtime/safari/Runtime.ts
  lib/api/src/runtime/safari/events.ts
  lib/api/src/storage/Storage.ts
  lib/api/src/storage/StorageProvider.ts
  lib/api/src/storage/chrome/Storage.ts
  lib/api/src/storage/events.ts
  lib/api/src/storage/extensions/Storage.ts
  lib/api/src/storage/safari/Storage.ts
  lib/api/src/tabs/Tabs.ts
  lib/api/src/tabs/TabsProvider.ts
  lib/api/src/tabs/chrome/Tab.ts
  lib/api/src/tabs/chrome/Tabs.ts
  lib/api/src/tabs/events.ts
  lib/api/src/tabs/extensions/Tab.ts
  lib/api/src/tabs/extensions/Tabs.ts
  lib/api/src/tabs/safari/Tab.ts
  lib/api/src/tabs/safari/Tabs.ts
Labels: beekeeping
