Repository exteranto/framework, pull requests merged in 2019-03, with the labels that each got.

#111 Bug tabs dont throw error
  lib/api/src/tabs/TabInterface.ts
  lib/api/src/tabs/chrome/Tab.ts
  lib/api/src/tabs/extensions/Tab.ts
  lib/api/src/tabs/safari/Tab.ts
  lib/api/test/spec/tabs/chrome.ts
  lib/api/test/spec/tabs/extensions.ts
  lib/api/test/spec/tabs/safari.ts
Labels: bug

#112 Bug active tab returns undefined if not set
  lib/api/src/tabs/Tabs.ts
  lib/api/src/tabs/exceptions.ts
  lib/api/test/spec/tabs/chrome.ts
  lib/api/test/spec/tabs/extensions.ts
  lib/api/test/spec/tabs/safari.ts
  lib/utils/src/cache/Cache.ts
  lib/utils/test/spec/cache/Cache.spec.ts
Labels: bug

#114 Feature tab favicon api
  lib/api/src/tabs/TabInterface.ts
  lib/api/src/tabs/chrome/Tab.ts
  lib/api/src/tabs/exceptions.ts
  lib/api/src/tabs/extensions/Tab.ts
  lib/api/src/tabs/safari/Tab.ts
  lib/api/test/spec/tabs/chrome.ts
  lib/api/test/spec/tabs/extensions.ts
  lib/api/test/spec/tabs/safari.ts
Labels: api coverage

#115 chrome and extensions now reject the send promise if unconnected
  lib/api/src/browserAction/index.ts
  lib/api/src/extension/index.ts
  lib/api/src/messaging/Messaging.ts
  lib/api/src/messaging/chrome/Messaging.ts
  lib/api/src/messaging/exceptions.ts
  lib/api/src/messaging/extensions/Messaging.ts
  lib/api/src/messaging/index.ts
  lib/api/src/runtime/index.ts
  lib/api/src/storage/index.ts
  lib/api/src/tabs/TabInterface.ts
  lib/api/src/tabs/chrome/Tab.ts
  lib/api/src/tabs/extensions/Tab.ts
  lib/api/test/spec/messaging/chrome.ts
  lib/api/test/spec/messaging/extensions.ts
Labels: bug

#121 Checks for Firefox browser
  lib/core/src/support/Utils.ts
  lib/core/test/spec/support/Utils.spec.ts
Labels: bug

#124 Feature tab updated info
  lib/api/src/runtime/safari/events.ts
  lib/api/src/tabs/TabChangeInfo.ts
  lib/api/src/tabs/chrome/events.ts
  lib/api/src/tabs/events.ts
  lib/api/src/tabs/extensions/events.ts
  lib/api/src/tabs/index.ts
  lib/api/src/tabs/safari/events.ts
  lib/api/test/spec/tabs/chrome.ts
  lib/api/test/spec/tabs/extensions.ts
  lib/api/test/spec/tabs/safari.ts
Labels: enhancement
